version: '3.5'

services:
  
  server:
    environment:
      - APP_SETTINGS=development
      - FLASK_APP=wsgi.py
      - FLASK_ENV=development
     
    command: flask run --host=0.0.0.0

  task_queue:
    restart: always
    build:
      context: ./server/tasks
      dockerfile: Dockerfile
    volumes:
      - ./server:/app
    command: celery -A tasks  --loglevel=debug