# base image
FROM python:3.6.5-slim

RUN mkdir /server

WORKDIR /server

ADD . .

# set working directory



# add and install requirements
COPY ./requirements.txt /server/requirements.txt
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

COPY . /server


